// Tel Aviv high-tech companies — curated seed list
// type: 'greenhouse' | 'lever' | 'workable' | 'html'
// slug: board slug used by the job platform API
// careersUrl: used for html type (fallback scraping)

const companies = [
  // ── Greenhouse ────────────────────────────────────────────────────────────
  { name: 'monday.com',      type: 'greenhouse', slug: 'monday' },
  { name: 'Wix',             type: 'greenhouse', slug: 'wix' },
  { name: 'Fiverr',          type: 'greenhouse', slug: 'fiverr' },
  { name: 'CyberArk',        type: 'greenhouse', slug: 'cyberark' },
  { name: 'Outbrain',        type: 'greenhouse', slug: 'outbrain' },
  { name: 'Taboola',         type: 'greenhouse', slug: 'taboola' },
  { name: 'AppsFlyer',       type: 'greenhouse', slug: 'appsflyer' },
  { name: 'JFrog',           type: 'greenhouse', slug: 'jfrog' },
  { name: 'Varonis',         type: 'greenhouse', slug: 'varonis' },
  { name: 'SentinelOne',     type: 'greenhouse', slug: 'sentinelone' },
  { name: 'Aqua Security',   type: 'greenhouse', slug: 'aquasecurity' },
  { name: 'Snyk',            type: 'greenhouse', slug: 'snyk' },
  { name: 'Gong',            type: 'greenhouse', slug: 'gong' },
  { name: 'Similarweb',      type: 'greenhouse', slug: 'similarweb' },
  { name: 'Payoneer',        type: 'greenhouse', slug: 'payoneer' },
  { name: 'WalkMe',          type: 'greenhouse', slug: 'walkme' },
  { name: 'Cato Networks',   type: 'greenhouse', slug: 'catonetworks' },
  { name: 'OwnBackup',       type: 'greenhouse', slug: 'ownbackup' },
  { name: 'BigPanda',        type: 'greenhouse', slug: 'bigpanda' },
  { name: 'Kaltura',         type: 'greenhouse', slug: 'kaltura' },
  { name: 'Armis',           type: 'greenhouse', slug: 'armissecurity' },
  { name: 'Pentera',         type: 'greenhouse', slug: 'pentera' },
  { name: 'Orca Security',   type: 'greenhouse', slug: 'orca' },
  { name: 'Innovid',         type: 'greenhouse', slug: 'innovid' },
  { name: 'DoubleVerify',    type: 'greenhouse', slug: 'doubleverify' },
  { name: 'Elementor',       type: 'greenhouse', slug: 'elementor' },
  { name: 'Papaya Global',   type: 'greenhouse', slug: 'papayaglobal' },
  { name: 'Global-e',        type: 'greenhouse', slug: 'global-e' },
  { name: 'LivePerson',      type: 'greenhouse', slug: 'liveperson' },
  { name: 'Cloudinary',      type: 'greenhouse', slug: 'cloudinary' },
  { name: 'Cybereason',      type: 'greenhouse', slug: 'cybereason' },
  { name: 'IronSource',      type: 'greenhouse', slug: 'ironsource' },
  { name: 'Nuvei',           type: 'greenhouse', slug: 'nuvei' },
  { name: 'ClickSoftware',   type: 'greenhouse', slug: 'clicksoftware' },
  { name: 'Perion',          type: 'greenhouse', slug: 'perion' },
  { name: 'Canopy',          type: 'greenhouse', slug: 'canopycare' },
  { name: 'XM Cyber',        type: 'greenhouse', slug: 'xmcyber' },
  { name: 'Skai',            type: 'greenhouse', slug: 'skai' },

  // ── Lever ─────────────────────────────────────────────────────────────────
  { name: 'Logz.io',         type: 'lever', slug: 'logzio' },
  { name: 'Coralogix',       type: 'lever', slug: 'coralogix' },
  { name: 'Imperva',         type: 'lever', slug: 'imperva' },
  { name: 'Deep Instinct',   type: 'lever', slug: 'deepinstinct' },
  { name: 'Sysdig',          type: 'lever', slug: 'sysdig' },
  { name: 'Axonius',         type: 'lever', slug: 'axonius' },
  { name: 'Dazz',            type: 'lever', slug: 'dazz' },

  // ── Workable ──────────────────────────────────────────────────────────────
  { name: 'Atera',           type: 'workable', slug: 'atera' },
  { name: 'Tipalti',         type: 'workable', slug: 'tipalti' },
  { name: 'Nayax',           type: 'workable', slug: 'nayax' },
  { name: 'Syte',            type: 'workable', slug: 'syte' },

  // ── HTML scraping (custom careers pages) ──────────────────────────────────
  { name: 'Check Point',     type: 'html', careersUrl: 'https://careers.checkpoint.com/jobs' },
  { name: 'Amdocs',          type: 'html', careersUrl: 'https://www.amdocs.com/careers/job-listings' },
  { name: 'NICE Systems',    type: 'html', careersUrl: 'https://www.nice.com/about/careers' },
  { name: 'Radware',         type: 'html', careersUrl: 'https://www.radware.com/careers/' },
  { name: 'Allot',           type: 'html', careersUrl: 'https://www.allot.com/company/careers/' },
  { name: 'Akamai',          type: 'html', careersUrl: 'https://www.akamai.com/careers' },
  // ── Auto-discovered ──
  { name: 'Magic Software', type: 'html', careersUrl: 'https://www.magicsoftware.com/careers' },
  { name: 'Riskified', type: 'html', careersUrl: 'https://www.riskified.com/careers' },
  { name: 'Sisense', type: 'greenhouse', slug: 'embed' },
  { name: 'Skybox Security', type: 'html', careersUrl: 'https://www.skyboxsecurity.com/careers' },
  { name: 'Viber', type: 'html', careersUrl: 'https://www.viber.com/careers' },
  { name: 'Gett', type: 'html', careersUrl: 'https://gett.com/careers' },
  { name: 'Supermetrics', type: 'html', careersUrl: 'https://www.supermetrics.com/careers' },
  { name: 'Salt Security', type: 'greenhouse', slug: 'embed' },
  { name: 'Namogoo', type: 'html', careersUrl: 'https://www.namogoo.com/careers' },
  { name: 'Augury', type: 'html', careersUrl: 'https://www.augury.com/careers' },
  { name: 'Hysolate', type: 'html', careersUrl: 'https://www.hysolate.com/careers' },
  { name: 'Duda', type: 'html', careersUrl: 'https://www.duda.co/careers' },
  { name: 'Panaya', type: 'html', careersUrl: 'https://www.panaya.com/careers' },
  { name: 'PerimeterX', type: 'html', careersUrl: 'https://www.perimeterx.com/careers' },
  { name: 'OurCrowd', type: 'html', careersUrl: 'https://www.ourcrowd.com/careers' },
  { name: 'Lightricks', type: 'html', careersUrl: 'https://www.lightricks.com/careers' },
  { name: 'Guesty', type: 'html', careersUrl: 'https://www.guesty.com/careers' },
  { name: 'Moovit', type: 'html', careersUrl: 'https://www.moovitapp.com/careers' },
  { name: 'Guardicore', type: 'html', careersUrl: 'https://www.guardicore.com/careers' },
  { name: 'Argus Cyber Security', type: 'html', careersUrl: 'https://argus-sec.com/careers' },
  { name: 'Tufin', type: 'html', careersUrl: 'https://www.tufin.com/careers' },
  { name: 'Fireblocks', type: 'greenhouse', slug: 'embed' },
  { name: 'IntSights', type: 'html', careersUrl: 'https://www.intsights.com/careers' },
  { name: 'Reblaze', type: 'html', careersUrl: 'https://www.reblaze.com/careers' },
  { name: 'SafeBreach', type: 'greenhouse', slug: 'embed' },
  { name: 'Checkmarx', type: 'html', careersUrl: 'https://www.checkmarx.com/careers' },
  { name: 'Hub Security', type: 'html', careersUrl: 'https://www.hubsecurity.com/careers' },
  { name: 'CYE', type: 'html', careersUrl: 'https://www.cye.io/careers' },
  { name: 'Silverfort', type: 'html', careersUrl: 'https://www.silverfort.com/careers' },
  { name: 'Indeni', type: 'lever', slug: 'bluecatnetworks' },
  { name: 'Perception Point', type: 'html', careersUrl: 'https://www.perception-point.io/careers' },
  { name: 'Claroty', type: 'html', careersUrl: 'https://www.claroty.com/careers' },
  { name: 'Intezer', type: 'html', careersUrl: 'https://www.intezer.com/careers' },
  { name: 'Ermetic', type: 'greenhouse', slug: 'tenableinc' },
  { name: 'SecuredTouch', type: 'html', careersUrl: 'https://www.securedtouch.com/careers' },
  { name: 'Polyrize', type: 'html', careersUrl: 'https://www.polyrize.com/careers' },
  { name: 'Minerva Labs', type: 'html', careersUrl: 'https://www.minerva-labs.com/careers' },
  { name: 'Wiz', type: 'html', careersUrl: 'https://www.wiz.io/careers' },
  { name: 'Avanan', type: 'html', careersUrl: 'https://www.avanan.com/careers' },
  { name: 'Sygnia', type: 'html', careersUrl: 'https://www.sygnia.co/careers' },
  { name: 'eToro', type: 'html', careersUrl: 'https://www.etoro.com/careers' },
  { name: 'Melio', type: 'html', careersUrl: 'https://www.meliopayments.com/careers' },
  { name: 'BlueVine', type: 'html', careersUrl: 'https://www.bluevine.com/careers' },
  { name: 'Unit', type: 'html', careersUrl: 'https://www.unit.co/careers' },
  { name: 'Fundbox', type: 'html', careersUrl: 'https://www.fundbox.com/careers' },
  { name: 'Curv', type: 'html', careersUrl: 'https://www.curv.co/careers' },
  { name: 'Pagaya', type: 'greenhouse', slug: 'pagaya' },
  { name: 'Gloat', type: 'html', careersUrl: 'https://www.gloat.com/careers' },
  { name: 'Thetaray', type: 'html', careersUrl: 'https://www.thetaray.com/careers' },
  { name: 'Rewire', type: 'html', careersUrl: 'https://www.rewire.to/careers' },
  { name: 'Personetics', type: 'html', careersUrl: 'https://www.personetics.com/careers' },
  { name: 'Finout', type: 'html', careersUrl: 'https://www.finout.io/careers' },
  { name: 'HoneyBook', type: 'greenhouse', slug: 'honeybook' },
  { name: 'Justt', type: 'html', careersUrl: 'https://www.justt.ai/careers' },
  { name: 'ChargeAfter', type: 'html', careersUrl: 'https://www.chargeafter.com/careers' },
  { name: 'Tabit', type: 'html', careersUrl: 'https://www.tabit.cloud/careers' },
  { name: 'Forter', type: 'html', careersUrl: 'https://www.forter.com/careers' },
  { name: 'Mesh Payments', type: 'html', careersUrl: 'https://www.meshpayments.com/careers' },
  { name: 'Pecan', type: 'html', careersUrl: 'https://www.pecan.ai/careers' },
  { name: 'Trullion', type: 'html', careersUrl: 'https://www.trullion.com/careers' },
  { name: 'Verbit', type: 'html', careersUrl: 'https://www.verbit.ai/careers' },
  { name: 'Celsius Network', type: 'html', careersUrl: 'https://www.celsius.network/careers' },
  { name: 'Crymbo', type: 'html', careersUrl: 'https://www.crymbo.com/careers' },
  { name: 'Nano-X', type: 'html', careersUrl: 'https://www.nanox.vision/careers' },
  { name: 'TytoCare', type: 'html', careersUrl: 'https://www.tytocare.com/careers' },
  { name: 'Healthy.io', type: 'html', careersUrl: 'https://www.healthy.io/careers' },
  { name: 'Insightec', type: 'html', careersUrl: 'https://www.insightec.com/careers' },
  { name: 'OrCam', type: 'html', careersUrl: 'https://www.orcam.com/careers' },
  { name: 'Aidoc', type: 'html', careersUrl: 'https://www.aidoc.com/careers' },
  { name: 'Nym Health', type: 'html', careersUrl: 'https://www.nym.health/careers' },
  { name: 'K Health', type: 'greenhouse', slug: 'khealthcareers' },
  { name: 'Scopio Labs', type: 'html', careersUrl: 'https://www.scopiolabs.com/careers' },
  { name: 'Nucleai', type: 'html', careersUrl: 'https://www.nucleai.ai/careers' },
  { name: 'Pulsenmore', type: 'html', careersUrl: 'https://www.pulsenmore.com/careers' },
  { name: 'Biobeat', type: 'html', careersUrl: 'https://www.bio-beat.com/careers' },
  { name: 'Binah.ai', type: 'html', careersUrl: 'https://www.binah.ai/careers' },
  { name: 'Medisafe', type: 'html', careersUrl: 'https://www.medisafe.com/careers' },
  { name: 'MobileODT', type: 'html', careersUrl: 'https://www.mobileodt.com/careers' },
  { name: 'Telesofia Medical', type: 'html', careersUrl: 'https://www.telesofia.com/careers' },
  { name: 'Oxitone', type: 'html', careersUrl: 'https://www.oxitone.com/careers' },
  { name: 'Rapid Medical', type: 'html', careersUrl: 'https://www.rapid-medical.com/careers' },
  { name: 'FeelBetter', type: 'html', careersUrl: 'https://www.feelbetter.health/careers' },
  { name: 'MediWound', type: 'html', careersUrl: 'https://www.mediwound.com/careers' },
  { name: 'MeMed', type: 'html', careersUrl: 'https://www.me-med.com/careers' },
  { name: 'CureMetrix', type: 'html', careersUrl: 'https://www.curemetrix.com/careers' },
  { name: 'Theranica', type: 'html', careersUrl: 'https://www.theranica.com/careers' },
  { name: 'NVIDIA Israel', type: 'html', careersUrl: 'https://www.nvidia.com/careers' },
  { name: 'AnyVision', type: 'html', careersUrl: 'https://www.anyvision.co/careers' },
  { name: 'SparkBeyond', type: 'html', careersUrl: 'https://www.sparkbeyond.com/careers' },
  { name: 'Via', type: 'greenhouse', slug: 'via' },
  { name: 'BeyondMinds', type: 'html', careersUrl: 'https://www.beyondminds.ai/careers' },
  { name: 'Hailo', type: 'html', careersUrl: 'https://www.hailo.ai/careers' },
  { name: 'Dataloop', type: 'html', careersUrl: 'https://www.dataloop.ai/careers' },
  { name: 'Cynet', type: 'html', careersUrl: 'https://www.cynet.com/careers' },
  { name: 'Explorium', type: 'html', careersUrl: 'https://www.explorium.ai/careers' },
  { name: 'H2O.ai', type: 'html', careersUrl: 'https://www.h2o.ai/careers' },
  { name: 'Deci', type: 'html', careersUrl: 'https://www.deci.ai/careers' },
  { name: 'Aporia', type: 'html', careersUrl: 'https://www.aporia.com/careers' },
  { name: 'AI21 Labs', type: 'html', careersUrl: 'https://www.ai21.com/careers' },
  { name: 'WekaIO', type: 'html', careersUrl: 'https://www.weka.io/careers' },
  { name: 'Nexar', type: 'html', careersUrl: 'https://www.nexar.com/careers' },
  { name: 'ClimaCell (Tomorrow.io)', type: 'html', careersUrl: 'https://www.tomorrow.io/careers' },
  { name: 'Jasper', type: 'html', careersUrl: 'https://www.jasper.ai/careers' },
  { name: 'EnsoData', type: 'workable', slug: 'ensodata' },
  { name: 'D-ID', type: 'html', careersUrl: 'https://www.d-id.com/careers' },
  { name: 'Lumenisity', type: 'html', careersUrl: 'https://www.lumenisity.com/careers' },
  { name: 'Tabnine', type: 'html', careersUrl: 'https://www.tabnine.com/careers' },
  { name: 'VocalZoom', type: 'html', careersUrl: 'https://www.vocalzoom.com/careers' },
  { name: 'Cheq', type: 'html', careersUrl: 'https://www.cheq.ai/careers' },
  { name: 'Gong.io', type: 'html', careersUrl: 'https://www.gong.io/careers' },
  { name: 'Roboteam', type: 'html', careersUrl: 'https://www.roboteam.com/careers' },
  { name: 'Autonomous Solutions', type: 'html', careersUrl: 'https://www.asirobots.com/careers' },
  { name: 'ReWalk Robotics', type: 'html', careersUrl: 'https://www.rewalk.com/careers' },
  { name: 'Bright Machines', type: 'html', careersUrl: 'https://www.brightmachines.com/careers' },
  { name: 'SixAI', type: 'html', careersUrl: 'https://www.sixai.com/careers' },
  { name: 'RoboTiCan', type: 'html', careersUrl: 'https://www.robotican.net/careers' },
  { name: 'Medtronic Israel', type: 'html', careersUrl: 'https://www.medtronic.com/careers' },
  { name: 'Breezometer', type: 'html', careersUrl: 'https://www.breezometer.com/careers' },
  { name: 'Skycure (Symantec)', type: 'html', careersUrl: 'https://www.broadcom.com/careers' },
  { name: 'Autofleet', type: 'workable', slug: 'j' },
  { name: 'Neura Robotics', type: 'html', careersUrl: 'https://www.neura-robotics.com/careers' },
  { name: 'EZRaider', type: 'html', careersUrl: 'https://www.ezraider.com/careers' },
  { name: 'UVeye', type: 'html', careersUrl: 'https://www.uveye.com/careers' },
  { name: 'Diagnostic Robotics', type: 'html', careersUrl: 'https://www.diagnostic-robotics.com/careers' },
  { name: 'Tactile Mobility', type: 'html', careersUrl: 'https://www.tactilemobility.com/careers' },
  { name: 'Foxsy', type: 'html', careersUrl: 'https://www.foxsy.ai/careers' },
  { name: 'TechSee', type: 'html', careersUrl: 'https://www.techsee.me/careers' },
  { name: 'Workiz', type: 'html', careersUrl: 'https://www.workiz.com/careers' },
  { name: 'MyndYou', type: 'html', careersUrl: 'https://www.myndyou.com/careers' },
  { name: 'Clevertech', type: 'html', careersUrl: 'https://www.clevertech.biz/careers' },
  { name: 'Vera', type: 'html', careersUrl: 'https://www.vera.com/careers' },
  { name: 'Satori', type: 'html', careersUrl: 'https://www.satoricyber.com/careers' },
  { name: 'Optimove', type: 'html', careersUrl: 'https://www.optimove.com/careers' },
  { name: 'Yotpo', type: 'html', careersUrl: 'https://www.yotpo.com/careers' },
  { name: 'Juno Journey', type: 'html', careersUrl: 'https://www.junojourney.com/careers' },
  { name: 'Simplex', type: 'html', careersUrl: 'https://www.simplex.com/careers' },
  { name: 'Voyantis', type: 'html', careersUrl: 'https://www.voyantis.ai/careers' },
  { name: 'Overwolf', type: 'html', careersUrl: 'https://www.overwolf.com/careers' },
  { name: 'Site123', type: 'html', careersUrl: 'https://www.site123.com/careers' },
  { name: 'Artlist', type: 'html', careersUrl: 'https://www.artlist.io/careers' },
  { name: 'Viber (Rakuten)', type: 'html', careersUrl: 'https://www.viber.com/careers' },
  { name: 'Powtoon', type: 'workable', slug: 'powtoon' },
  { name: 'Playtika', type: 'html', careersUrl: 'https://www.playtika.com/careers' },
  { name: 'Lumenis', type: 'html', careersUrl: 'https://www.lumenis.com/careers' },
  { name: 'Mobileye', type: 'html', careersUrl: 'https://www.mobileye.com/careers' },
  { name: 'Autotalks', type: 'html', careersUrl: 'https://www.autotalks.com/careers' },
  { name: 'Innoviz Technologies', type: 'html', careersUrl: 'https://www.innoviz.tech/careers' },
  { name: 'Cognata', type: 'html', careersUrl: 'https://www.cognata.com/careers' },
  { name: 'Upstream Security', type: 'html', careersUrl: 'https://www.upstream.auto/careers' },
  { name: 'Ormat Technologies', type: 'html', careersUrl: 'https://www.ormat.com/careers' },
  { name: 'Electreon', type: 'html', careersUrl: 'https://www.electreon.com/careers' },
  { name: 'Eco Wave Power', type: 'html', careersUrl: 'https://www.ecowavepower.com/careers' },
  // ── Auto-discovered ──
  { name: '365scores', type: 'html', careersUrl: 'https://www.365scores.com/careers' },
  { name: 'Align', type: 'html', careersUrl: 'https://www.aligntech.com/careers' },
  { name: 'Apple', type: 'html', careersUrl: 'https://www.apple.com/careers' },
  { name: 'Applied Materials', type: 'html', careersUrl: 'https://www.appliedmaterials.com/careers' },
  { name: 'Autodesk', type: 'html', careersUrl: 'https://www.autodesk.com/careers' },
  { name: 'Axilion', type: 'html', careersUrl: 'https://www.axilion.com/careers' },
  { name: 'Bright Data', type: 'html', careersUrl: 'https://www.brightdata.com/careers' },
  { name: 'Bringg', type: 'html', careersUrl: 'https://www.bringg.com/careers' },
  { name: 'Citi', type: 'html', careersUrl: 'https://www.citigroup.com/careers' },
  { name: 'CloudShare', type: 'html', careersUrl: 'https://www.cloudshare.com/careers' },
  { name: 'Cognyte', type: 'html', careersUrl: 'https://www.cognyte.com/careers' },
  { name: 'Contentsquare', type: 'lever', slug: 'contentsquare' },
  { name: 'Cross River', type: 'greenhouse', slug: 'crossriverbank' },
  { name: 'Cycode', type: 'html', careersUrl: 'https://www.cycode.com/careers' },
  { name: 'Cymulate', type: 'html', careersUrl: 'https://www.cymulate.com/careers' },
  { name: 'Dell Technologies', type: 'html', careersUrl: 'https://www.dell.com/careers' },
  { name: 'Deloitte', type: 'lever', slug: 'deloitte' },
  { name: 'Dome9', type: 'html', careersUrl: 'https://dome9.com/careers' },
  { name: 'DoorLoop', type: 'html', careersUrl: 'https://www.doorloop.com/careers' },
  { name: 'Driivz', type: 'html', careersUrl: 'https://www.driivz.com/careers' },
  { name: 'DriveNets', type: 'html', careersUrl: 'https://www.drivenets.com/careers' },
  { name: 'EY', type: 'html', careersUrl: 'https://www.ey.com/careers' },
  { name: 'Flywire', type: 'html', careersUrl: 'https://www.flywire.com/careers' },
  { name: 'General Motors', type: 'html', careersUrl: 'https://www.gm.com/careers' },
  { name: 'GrubHub', type: 'html', careersUrl: 'https://www.grubhub.com/careers' },
  { name: 'HiredScore', type: 'html', careersUrl: 'https://www.hiredscore.com/careers' },
  { name: 'ICE - Intercontinental Exchange', type: 'html', careersUrl: 'https://www.ice.com/careers' },
  { name: 'Intuit', type: 'html', careersUrl: 'https://www.intuit.com/careers' },
  { name: 'Kenshoo', type: 'html', careersUrl: 'https://www.skai.io/careers' },
  { name: 'Lusha', type: 'html', careersUrl: 'https://www.lusha.com/careers' },
  { name: 'Mirato', type: 'html', careersUrl: 'https://www.mirato.com/careers' },
  { name: 'Natural Intelligence', type: 'html', careersUrl: 'https://www.naturalint.com/careers' },
  { name: 'NetApp', type: 'html', careersUrl: 'https://www.netapp.com/careers' },
  { name: 'Nexxen', type: 'html', careersUrl: 'https://www.nexxen.com/careers' },
  { name: 'Noname Security', type: 'html', careersUrl: 'https://www.nonamesecurity.com/careers' },
  { name: 'NVIDIA', type: 'html', careersUrl: 'https://www.nvidia.com/careers' },
  { name: 'Okta', type: 'html', careersUrl: 'https://www.okta.com/careers' },
  { name: 'Oracle', type: 'html', careersUrl: 'https://www.oracle.com/careers' },
  { name: 'Palo Alto Networks', type: 'html', careersUrl: 'https://www.paloaltonetworks.com/careers' },
  { name: 'Pepper', type: 'html', careersUrl: 'https://www.pepper.co.il/careers' },
  { name: 'Philips', type: 'html', careersUrl: 'https://www.philips.com/careers' },
  { name: 'Pixellot', type: 'html', careersUrl: 'https://www.pixellot.tv/careers' },
  { name: 'PlainID', type: 'html', careersUrl: 'https://www.plainid.com/careers' },
  { name: 'Planck', type: 'html', careersUrl: 'https://www.planckdata.com/careers' },
  { name: 'PlayStudios', type: 'html', careersUrl: 'https://www.playstudios.com/careers' },
  { name: 'Poalim IT Division', type: 'html', careersUrl: 'https://www.bankhapoalim.co.il/careers' },
  { name: 'Preempt (A CrowdStrike Company)', type: 'html', careersUrl: 'https://www.crowdstrike.com/careers' },
  { name: 'proteanTecs', type: 'html', careersUrl: 'https://www.proteantecs.com/careers' },
  { name: 'Qwilt', type: 'html', careersUrl: 'https://www.qwilt.com/careers' },
  { name: 'Rubrik', type: 'html', careersUrl: 'https://www.rubrik.com/careers' },
  { name: 'SailPoint', type: 'html', careersUrl: 'https://www.sailpoint.com/careers' },
  { name: 'Salesforce', type: 'html', careersUrl: 'https://www.salesforce.com/careers' },
  { name: 'SciPlay', type: 'html', careersUrl: 'https://www.sciplay.com/careers' },
  { name: 'ServiceNow', type: 'html', careersUrl: 'https://www.servicenow.com/careers' },
  { name: 'Singular', type: 'html', careersUrl: 'https://www.singular.net/careers' },
  { name: 'TandemG', type: 'html', careersUrl: 'https://www.tandemg.com/careers' },
  { name: 'Tonkean', type: 'html', careersUrl: 'https://www.tonkean.com/careers' },
  { name: 'Trax Image Recognition', type: 'html', careersUrl: 'https://www.traxretail.com/careers' },
  { name: 'Vayyar', type: 'workable', slug: 'vayyar' },
  { name: 'Veeva Crossix', type: 'html', careersUrl: 'https://www.veeva.com/careers' },
  { name: 'Verint', type: 'html', careersUrl: 'https://www.verint.com/careers' },
  // ── Auto-discovered ──
  { name: 'Biosense Webster', type: 'html', careersUrl: 'https://www.biosensewebster.com/careers' },
  { name: 'Broadcom', type: 'html', careersUrl: 'https://www.broadcom.com/careers' },
  { name: 'CEVA', type: 'html', careersUrl: 'https://www.ceva-dsp.com/careers' },
  { name: 'DELL', type: 'html', careersUrl: 'https://www.dell.com/careers' },
  { name: 'ebay', type: 'html', careersUrl: 'https://www.ebay.com/careers' },
  { name: 'Given Imaging', type: 'html', careersUrl: 'https://www.medtronic.com/careers' },
  { name: 'IBM', type: 'html', careersUrl: 'https://www.ibm.com/careers' },
  { name: 'Innoviz', type: 'html', careersUrl: 'https://www.innoviz.tech/careers' },
  { name: 'Mellanox', type: 'html', careersUrl: 'https://www.mellanox.com/careers' },
  { name: 'Microsoft', type: 'html', careersUrl: 'https://www.microsoft.com/careers' },
  { name: 'PayPal', type: 'html', careersUrl: 'https://www.paypal.com/careers' },
  { name: 'PerSimiO Ltd', type: 'html', careersUrl: 'https://www.persimio.com/careers' },
  { name: 'Playtica', type: 'html', careersUrl: 'https://www.playtika.com/careers' },
  { name: 'Qualcomm', type: 'html', careersUrl: 'https://www.qualcomm.com/careers' },
  { name: 'Syqe Medical', type: 'html', careersUrl: 'https://www.syqe.com/careers' },
  { name: 'VMWARE', type: 'html', careersUrl: 'https://www.vmware.com/careers' },
  // ── Auto-discovered ──
  { name: 'AI-BI', type: 'html', careersUrl: 'https://www.ai-bi.co.il/careers' },
  { name: 'apiiro', type: 'html', careersUrl: 'https://apiiro.com/careers' },
]

export default companies
